### PR TITLE
Generate 1.7.11 diff sample

### PR DESCRIPTION
**Pull request by rkenzhebekov**
Generate phx v1.7.11 changes

### CODE REVIEW

**Comment by danschultzer** [comment]
There's a lot missing here. I think you'll need to `mix phx_diff.gen.sample` for each of [the args](https://www.phoenixdiff.org)). Would be nice to have a mix task or makefile task that ensures all of them gets generated in a single command though.

**Comment by aaronrenner** [comment]
Thank you!

**Comment by danschultzer** [comment]
Looks like the hero icons where missing: https://www.phoenixdiff.org/compare/1.7.10%20--umbrella...1.7.11%20--umbrella

**Comment by danschultzer** [comment]
Oh nevermind that's how phoenix 1.7.11 is works now: https://github.com/phoenixframework/phoenix/pull/5634

All good!

**Pull request merged**
